### ISSUE TITLE
EHOST error when using foreman as the mco discovery

### ISSUE THREAD

**Issue by rashkinadze** [cernops/mcollective-foreman#8]
The username/password combination that I have attempted on the command line works fine in the Foreman ui, but errors out with mco.

$ mco rpc rpcutil ping --dm=foreman --do='name=host.example.com' -v
Discovering hosts using the foreman method .... Username:
xxx
Password:

The rpc application failed to run: uninitialized constant Errno::EHOST

uninitialized constant Errno::EHOST (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/discovery/foreman.rb:55:in `rescue in get_ssl'  <----
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/discovery/foreman.rb:50:in`get_ssl'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/discovery/foreman.rb:38:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/discovery/foreman.rb:29:in`discover'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/discovery.rb:134:in `discover'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/client.rb:151:in`discover'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/rpc/client.rb:548:in `discover'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/application/rpc.rb:112:in`main'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/application.rb:293:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/lib/mcollective/applications.rb:23:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.8.4/bin/mco:33:in `<top (required)>'
    from /usr/local/bin/mco:23:in`load'
    from /usr/local/bin/mco:23:in `<main>'

xxx-15-MacBook-Pro: xxx$ grep foreman ~/.mcollective
plugin.foreman.url = https://katello:443
plugin.foreman.ssl_cert = /Users/xxx/.puppet/ssl/certs/xxx-15-macbook-pro.local.pem
plugin.foreman.ssl_key  = /Users/xx/.puppet/ssl/private_keys/xxx-15-macbook-pro.local.pem
plugin.foreman.use_krb  = 0

**Comment by reguero** [comment]
This issue was due to truncated exception names in rescue statements.
It should be fixed now.      Best regards  ...Ignacio...

**Comment by rashkinadze** [comment]
Thanks for updating this.  I know get a different error about certificate verification.  The config assumes that there is a /var/puppet and that is where the ca.crt should be.  That's not the case on my system.

The rpc application failed to run: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'  <----
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/discovery/foreman.rb:71:in `block in get_ssl'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/discovery/foreman.rb:70:in `get_ssl'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/discovery/foreman.rb:57:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/discovery/foreman.rb:48:in `discover'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/discovery.rb:134:in `discover'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/client.rb:151:in `discover'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/rpc/client.rb:548:in `discover'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/application/rpc.rb:112:in `main'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/application.rb:293:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/lib/mcollective/applications.rb:23:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/mcollective-client-2.9.1/bin/mco:33:in `<top (required)>'
	from /usr/local/bin/mco:23:in `load'
	from /usr/local/bin/mco:23:in `<main>'

**Comment by reguero** [comment]
Hi @rashkinadze,
If you use SSL, you need to have the certificates somewhere. The location of the certificates can be configured with the plugin.foreman.ssl_cert and plugin.foreman.ssl_key settings in  the mcollective/client.cfg.
I think that by default you have
plugin.foreman.ssl_cert = /var/lib/puppet/ssl/certs/<%= fqdn %>.pem
plugin.foreman.ssl_key  = /var/lib/puppet/ssl/private_keys/<%= fqdn %>.pem
but you can change the location to wherever makes sense to you.

**Comment by rashkinadze** [comment]
Thanks for responding.  I did confirm that I had set the ssl keys in .mcollective.  I know that these files exist.  Is it possible that they aren’t being read because the module by default assumes that puppet is all in /var/lib/puppet ...

plugin.foreman.url = https://katello.stsky.biz:443
plugin.foreman.ssl_cert = /Users/rashkinadze/.puppet/ssl/certs/rimmas-15-macbook-pro.local.pem
plugin.foreman.ssl_key  = /Users/rashkinadze/.puppet/ssl/private_keys/rimmas-15-macbook-pro.local.pem
plugin.foreman.use_krb  = 0

**Comment by reguero** [comment]
Right, thanks for your report.
I think the certificate validation fails in your case because the ssl_ca is hardcoded to the /var/lib/puppet hierarchy which is a flaw.
I have done a fix that allows to configure the ssl CA with setting plugin.foreman.ssl_ca.
